export const meta = {
  name: 'lead-hunter-qa',
  description: 'QA: выборочная сверка телефонов с source_url',
  phases: [{ title: 'QA' }],
}
const SCHEMA = {
  type: 'object',
  required: ['verdicts'],
  properties: {
    verdicts: {
      type: 'array',
      items: {
        type: 'object',
        required: ['phone', 'verdict'],
        properties: {
          phone: { type: 'string' },
          verdict: { enum: ['pass', 'fail', 'page_dead'] },
          note: { type: 'string', maxLength: 150 },
        },
      },
    },
  },
}
const TASKS = [
  { label: "qa_1", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77758863581\", \"school\": \"Technosphera.kz (IT-курсы)\", \"source_url\": \"https://karaganda.spravker.ru/uchebnyie-tsentryi/\"}, {\"phone\": \"+77770332714\", \"school\": \"Профессионал\", \"source_url\": \"https://uralsk.spravker.ru/uchebnyie-tsentryi/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_2", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77010668388\", \"school\": \"Nur Amir\", \"source_url\": \"https://atyrau.spravker.ru/detskie-razvivaiushchie/\"}, {\"phone\": \"+77085825350\", \"school\": \"Познавайка\", \"source_url\": \"https://uralsk.spravker.ru/uchebnyie-tsentryi/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_3", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77078801983\", \"school\": \"Арман\", \"source_url\": \"https://taraz.spravker.ru/detskie-razvivaiushchie/\"}, {\"phone\": \"+77076608500\", \"school\": \"Дарын\", \"source_url\": \"https://semei.spravker.ru/detskie-razvivaiushchie/daryn.htm\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_4", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77781689069\", \"school\": \"Zerdeli Kyzylorda\", \"source_url\": \"https://kyzyloroda.spravker.ru/detskie-razvivaiushchie/\"}, {\"phone\": \"+77079895244\", \"school\": \"Gaucho Study\", \"source_url\": \"https://karaganda.spravker.ru/obuchenie-za-rubezhom/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_5", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77779500022\", \"school\": \"UChina\", \"source_url\": \"https://uchina.kz/uchina\"}, {\"phone\": \"+77087226076\", \"school\": \"Generation Centre\", \"source_url\": \"https://generation-centre.kz/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_6", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77014284886\", \"school\": \"M&K\", \"source_url\": \"http://mks.kz/\"}, {\"phone\": \"+996551447143\", \"school\": \"IQ Consulting\", \"source_url\": \"https://iq-consulting.kg/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_7", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77014101505\", \"school\": \"Globus Education\", \"source_url\": \"https://globusedu.kz/\"}, {\"phone\": \"+77076104040\", \"school\": \"Ivy Course\", \"source_url\": \"https://ivycourse.kz/ru/welcome\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_8", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+996555127155\", \"school\": \"INTENSIVE\", \"source_url\": \"https://courses.kg/english/intensive/\"}, {\"phone\": \"+77086507578\", \"school\": \"Umbrella\", \"source_url\": \"https://pavlodar.jsprav.ru/izuchenie-anglijskogo-yazyika/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_9", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+996322220529\", \"school\": \"Taylor Institute\", \"source_url\": \"https://englishhere.ru/komp/institut-tejlora-obrazovatelnyj-tsentr-osh\"}, {\"phone\": \"+77052044759\", \"school\": \"Angliyskiy detyam\", \"source_url\": \"https://kursy-shymkent.kz/course/foreign/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_10", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77086166841\", \"school\": \"Lingua Studio\", \"source_url\": \"https://aktau.jsprav.ru/izuchenie-anglijskogo-yazyika/\"}, {\"phone\": \"+77054830493\", \"school\": \"Easy Communication\", \"source_url\": \"https://kursy-shymkent.kz/course/foreign/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_11", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+996508441001\", \"school\": \"Babylon\", \"source_url\": \"https://englishhere.ru/komp/babylon-uchebnyj-tsentr-osh\"}, {\"phone\": \"+77753500196\", \"school\": \"Ucheniki.kz\", \"source_url\": \"https://aktobe.spravker.ru/uchebnyie-tsentryi/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_12", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77132708088\", \"school\": \"Ақылды бала\", \"source_url\": \"https://aktobe.iseducate.ru/uchebnye-tsentry/\"}, {\"phone\": \"+77054444141\", \"school\": \"Интеллект\", \"source_url\": \"https://mestam.info/kz/uralsk-11092/mesto/4577017-intellekt-aitalieva-4\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_13", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77084714346\", \"school\": \"Bolashaq\", \"source_url\": \"https://aktobe.spravker.ru/uchebnyie-tsentryi/\"}, {\"phone\": \"+77471869499\", \"school\": \"Бәйтерек\", \"source_url\": \"https://uralsk.spravker.ru/uchebnyie-tsentryi/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_14", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77015702173\", \"school\": \"Білім\", \"source_url\": \"https://taplink.cc/bilim_aktobe\"}, {\"phone\": \"+77774249923\", \"school\": \"Юланил\", \"source_url\": \"https://uralsk.spravker.ru/uchebnyie-tsentryi/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." },
  { label: "qa_15", prompt: "Ты — QA-верификатор базы контактов. Проверь, что телефоны реально присутствуют на страницах-источниках.\n\nСтроки для проверки (JSON): [{\"phone\": \"+77471140468\", \"school\": \"Qazaq bilim ordasy\", \"source_url\": \"https://petropavlovsk-kz.spravker.ru/detskie-razvivaiushchie/\"}, {\"phone\": \"+77073047899\", \"school\": \"Manhattan\", \"source_url\": \"https://manhattan-school-translator.kz/\"}]\n\nДля КАЖДОЙ строки:\n1. Загрузи source_url. Сначала детерминированно:\n   cd \"/Users/omirgaliramazan/база контактов/lead-hunter\" && python3 tools/fetch_extract.py --urls \"<source_url>\"\n   Если скрипт вернул этот телефон (поле phone совпадает) — verdict=\"pass\".\n2. Если скрипт не нашёл или страница не отдалась — попробуй WebFetch того же URL с вопросом, какие телефоны/WhatsApp указаны на странице. Совпадение цифр номера (форматирование не важно: +7 777 216 67 89 == +77772166789) — verdict=\"pass\".\n3. Страница не открывается совсем (обе попытки) — verdict=\"page_dead\".\n4. Страница открылась, но номера там нет — verdict=\"fail\".\nНе засчитывай pass по памяти или догадке — только по реальному содержимому страницы этой сессии.\nВерни JSON-массив вердиктов по схеме structured output." }
]
phase('QA')
const results = await parallel(TASKS.map(t => () =>
  agent(t.prompt, { label: t.label, phase: 'QA', schema: SCHEMA })))
const verdicts = results.filter(Boolean).flatMap(r => r.verdicts)
const count = v => verdicts.filter(x => x.verdict === v).length
return { total: verdicts.length, pass: count('pass'), fail: count('fail'),
         page_dead: count('page_dead'),
         failures: verdicts.filter(x => x.verdict !== 'pass') }
